# Site settings
title: Freddy Friends
description: A blog about our sailing adventures around the world
url: "http://yourdomain.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Collections directory
collections_dir: _collections

# Collections
collections:
  updates:
    output: false
  stories:
    output: true
    permalink: /stories/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "post"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
      
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include _pages directory
include:
  - _pages
